### ISSUE TITLE
PDF generation failing on IIS node

### ISSUE THREAD

**Issue by ankitchoudary** [KerimG/node-DocTo#1]
Hi,

I am trying to generate PDF from a docx file, it's working fine locally, but on IIS node server, it's giving following error:
{"error":{"killed":false,"code":220,"signal":null,"cmd":"C:\\Program
Files\\iisnode\\www\\PdfGenerator\\node_modules\\node-docto\\lib\\docto.exe -f C:\\Program
Files\\iisnode\\www\\PdfGenerator\\tmp\\Backup and Recovery-1603187462867.docx -O C:\\Program
Files\\iisnode\\www\\PdfGenerator\\tmp\\Backup and Recovery-1603187462867.docx.pdf -T wdFormatPDF -R true"},"stderr":""}
Can anyone help me in resolving this.

**Comment by tobya** [comment]
I think you may need to put your paths inside quotes as they contain spaces

Something like

 > docto.exe -f "C:\Program Files\iisnode\www\PdfGenerator\tmp\Backup and Recovery-1603187462867.docx" -O "C:\Program Files\iisnode\www\PdfGenerator\tmp\Backup and Recovery-1603187462867.docx.pdf" -T wdFormatPDF -R true


Also sometimes if docto works on command line but not from IIS its usually to do with permissions of the user your website runs under.

**Comment by ankitchoudary** [comment]
@tobya , I tried from command line as well. Please find below the details:
C:\Program Files\iisnode\www\PdfGenerator\node_modules\node-docto\lib>docto.exe -f "%programfiles%\\iisnode\\www\\PdfGenerator\\tmp\\Backup and Recovery-1603212397612.docx" -O "%programfiles%\\iisnode\\www\\PdfGenerator\\tmp\\output.pdf" -T wdFormatPDF
[INFO]   FileToConvert:C:\Program Files\iisnode\www\PdfGenerator\tmp\Backup and Recovery-1603212397612.docx
[INFO]   OutputFile:C:\Program Files\iisnode\www\PdfGenerator\tmp\output.pdf
[INFO]   Ext17
*******************************************
Error: EOleException  We can't save this file because it's read-only.
To keep your changes, you'll need to save the document with a new name or in a different location
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************

**Comment by tobya** [comment]
Could you provide me with some more information

Take a look at the error and see if you can find more information that
might be useful to me.

**Comment by ankitchoudary** [comment]
@tobya , I checked this error, It normally occurred when we try to save a read-only word document.

Also I saw a C# sample code for docx to pdf conversion using Word Interop, there it was mentioned to set the readOnly property to true:
// Interop requires objects.
            object oMissing = System.Reflection.Missing.Value;
            object isVisible = true;
            object readOnly = true;     // Does not cause any word dialog to show up
            //object readOnly = false;  // Causes a word object dialog to show at the end of the conversion

**Comment by ankitchoudary** [comment]
Thanks @tobya , It's working now. You were right issue was with the access level of IIS user.
